dist: trusty
sudo: required

os:
  - linux

language: python

python:
  - "3.6"

env:
  global:
    - CC=clang
    - CXX=clang++

# Bazel dependencies.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - pkg-config
      - zip
      - g++
      - zlib1g-dev unzip python


before_install:
  # Install bazel.
  - wget https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel_0.20.0-linux-x86_64.deb -O bazel.deb
  - sudo dpkg -i bazel.deb
  # # Install POCL OpenCL implementation.
  # - sudo apt-get install -y pkg-config libltdl3-dev libhwloc-dev llvm-dev clang libclang-dev ocl-icd-opencl-dev libedit-dev
  # - wget http://portablecl.org/downloads/pocl-0.12.tar.gz
  # - tar xzf pocl-0.12.tar.gz
  # - cd pocl-0.12/ && ./configure && make && sudo make install && cd ..
  # - sudo rm -r pocl-0.12


script:
  - bazel build //gpu/cldrive
